### ISSUE TITLE
ERROR: Running into issue with Preview Chooser for Fabric

### ISSUE THREAD

**Issue by sedetweiler** [chrisgoringe/cg-image-picker#54]
Using a simple chooser on the 2nd pass to give the pos and neg latents and get this error:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_fabric\nodes.py", line 181, in sample
    return KSamplerFABRICAdv().sample(*args, **kwargs)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_fabric\nodes.py", line 138, in sample
    return fabric_sample(*args, **kwargs)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_fabric\fabric\fabric.py", line 42, in fabric_sample
    timesteps = get_timesteps(model, steps, sampler_name, scheduler, denoise)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_fabric\fabric\unet.py", line 23, in get_timesteps
    return model_wrap.sigma_to_discrete_timestep(sampler.sigmas)
  File "D:\stable_diffusion\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CFGNoisePredictor' object has no attribute 'sigma_to_discrete_timestep'

Prompt executed in 70.70 seconds
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
```

**Comment by sedetweiler** [comment]
Here is the complete workflow

[workflow (39).json](https://github.com/chrisgoringe/cg-image-picker/files/13325760/workflow.39.json)

**Comment by netdzynr** [comment]
Receiving the same error here using the provided example workflow. Comfy appears to be up to date (git pull).

**Comment by chrisgoringe** [comment]
Does the problem happen if you use fabric without the image chooser node? It looks like an issue with fabric and the recent comfy updates.

**Comment by sedetweiler** [comment]
I have not tried it without the chooser, as that really makes this approachable by most people.  I want to make a video on this for my channel, so I need it to be something people can "get" and implement.

**Comment by chrisgoringe** [comment]
I understand. 

But the bug is in Fabric - it isn't working at all at the moment, it has nothing to do with the image chooser! If you take the image chooser out the same error still happens.

It's been logged as an issue with the Fabric author, and there is a PR to fix it, https://github.com/ssitu/ComfyUI_fabric/issues/13 so hopefully the Fabric nodes will get updated very soon, and this problem will go away.
