### ISSUE TITLE
Why does it automatically download "cg_custom_core" when updating "cg image picker"

### ISSUE THREAD

**Issue by laidingq** [chrisgoringe/cg-image-picker#78]
Why does it automatically download "cg_custom_core" when updating "cg image picker"

**Comment by EricRollei** [comment]
@laidingq  there's info in the readme
I came here because my cg_custom_core doesn't install on my comfyUI application.   The image picker still works so not too much an issue, however, I'm not able to update it using git pull.  And I can't see it in the comfy manager either.  Hmm

**Comment by chrisgoringe** [comment]
'cg_custom_core' is no longer required by image picker - there is no reference to it anywhere in the codebase. So I'm puzzled what people are seeing....

**Comment by EricRollei** [comment]
This is from my comfyui log

[2024-02-19 10:32] Traceback (most recent call last):
  File "A:\Comfy_Dec\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\Comfy_Dec\ComfyUI\custom_nodes\cg_custom_core\__init__.py", line 15, in <module>
    os.remove(old_code_location)
PermissionError: [WinError 5] Access is denied: 'A:\\Comfy_Dec\\ComfyUI\\web\\extensions\\cg-nodes'
[2024-02-19 10:32] 
[2024-02-19 10:32] Cannot import A:\Comfy_Dec\ComfyUI\custom_nodes\cg_custom_core module for custom nodes: [WinError 5] Access is denied: 'A:\\Comfy_Dec\\ComfyUI\\web\\extensions\\cg-nodes'
[2024-02-19 10:32] Error:

**Comment by EricRollei** [comment]
I haven't done any new installs of your other custom nodes or updates so don't know about it trying to download the cg_custom_nodes.   
So I can delete the folder from my custom nodes and it won't affect the image picker or use anywhere nodes?

**Comment by chrisgoringe** [comment]
I think you should be able to delete the cg_custom_core folder from custom_nodes, yes. 

The custom_core was a badly executed attempt to share code between custom_nodes. Turns out it's better just to copy the files!
